version: '3'

services:
  web:
    build: .
    ports:
      - "3003:3003"
    networks:
      - local_network
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev -- -p 3003
networks:
  local_network:
    external: true
